/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package principal;

import java.awt.GraphicsEnvironment;

/**
 *
 * @author JAK LIZCANO
 */
public class Seleccion extends javax.swing.JFrame {

    /**
     * Creates new form Selec
     */
    public Seleccion() {
        initComponents();
    }
    
    public void emergente() {
        Tecnica seleccion = new Tecnica(this, false);
        java.awt.GraphicsDevice[] devices = GraphicsEnvironment.getLocalGraphicsEnvironment().getScreenDevices();
        devices[ 1 ].setFullScreenWindow(seleccion);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        caracteristicas2 = new javax.swing.JLabel();
        caracteristicas1 = new javax.swing.JLabel();
        habitat = new javax.swing.JLabel();
        caracteristicas = new javax.swing.JLabel();
        general1 = new javax.swing.JLabel();
        cerrar = new javax.swing.JLabel();
        general = new javax.swing.JLabel();
        habitat1 = new javax.swing.JLabel();
        habitat2 = new javax.swing.JLabel();
        pez = new javax.swing.JLabel();
        general3 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setMaximumSize(new java.awt.Dimension(1366, 768));
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setUndecorated(true);
        setOpacity(0.0F);

        caracteristicas2.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        caracteristicas2.setForeground(new java.awt.Color(255, 255, 255));
        caracteristicas2.setText("CARACTERÍSTICAS");
        jLayeredPane1.add(caracteristicas2);
        caracteristicas2.setBounds(350, 500, 240, 29);

        caracteristicas1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        caracteristicas1.setForeground(new java.awt.Color(255, 255, 255));
        caracteristicas1.setText("CARACTERÍSTICAS");
        jLayeredPane1.add(caracteristicas1);
        caracteristicas1.setBounds(350, 630, 240, 29);

        habitat.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        habitat.setForeground(new java.awt.Color(255, 255, 255));
        habitat.setText("HABITAT Y ALIMENTACIÓN");
        jLayeredPane1.add(habitat);
        habitat.setBounds(640, 570, 340, 29);

        caracteristicas.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        caracteristicas.setForeground(new java.awt.Color(255, 255, 255));
        caracteristicas.setText("CARACTERÍSTICAS");
        jLayeredPane1.add(caracteristicas);
        caracteristicas.setBounds(350, 560, 240, 29);

        general1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        general1.setForeground(new java.awt.Color(255, 255, 255));
        general1.setText("GENERAL");
        jLayeredPane1.add(general1);
        general1.setBounds(150, 630, 130, 29);

        cerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        cerrar.setAlignmentY(0.0F);
        cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrarMouseClicked(evt);
            }
        });
        jLayeredPane1.add(cerrar);
        cerrar.setBounds(1290, 10, 64, 64);

        general.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        general.setForeground(new java.awt.Color(255, 255, 255));
        general.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        general.setText("NOMBRES Y CLASIFICACION");
        general.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                generalMouseClicked(evt);
            }
        });
        jLayeredPane1.add(general);
        general.setBounds(30, 440, 560, 30);

        habitat1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        habitat1.setForeground(new java.awt.Color(255, 255, 255));
        habitat1.setText("HABITAT Y ALIMENTACIÓN");
        jLayeredPane1.add(habitat1);
        habitat1.setBounds(630, 630, 340, 29);

        habitat2.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        habitat2.setForeground(new java.awt.Color(255, 255, 255));
        habitat2.setText("HABITAT Y ALIMENTACIÓN");
        jLayeredPane1.add(habitat2);
        habitat2.setBounds(630, 500, 340, 29);

        pez.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pez.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/peces/fish0.png"))); // NOI18N
        pez.setAlignmentY(0.0F);
        pez.setMaximumSize(new java.awt.Dimension(720, 300));
        pez.setMinimumSize(new java.awt.Dimension(720, 300));
        pez.setPreferredSize(new java.awt.Dimension(720, 300));
        jLayeredPane1.add(pez);
        pez.setBounds(323, 100, 720, 300);

        general3.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        general3.setForeground(new java.awt.Color(255, 255, 255));
        general3.setText("GENERAL");
        jLayeredPane1.add(general3);
        general3.setBounds(160, 560, 130, 29);

        fondo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fseleccion.jpg"))); // NOI18N
        fondo.setAlignmentY(0.0F);
        fondo.setOpaque(true);
        jLayeredPane1.add(fondo);
        fondo.setBounds(0, 0, 1366, 768);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseClicked
        // TODO add your handling code here:
        //        Explode ex = new Explode( null, tecnica );
        //        ex.stopEmergente();
        Explode ex = new Explode( this, null );
        ex.stop();
    }//GEN-LAST:event_cerrarMouseClicked

    private void generalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_generalMouseClicked
        // TODO add your handling code here:
        //        try {
            //            cliente.seleccionado("1");
            //        } catch (IOException ex) {
            //            Logger.getLogger(Seleccion.class.getName()).log(Level.SEVERE, null, ex);
            //        }
    }//GEN-LAST:event_generalMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Seleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Seleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Seleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Seleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Seleccion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel caracteristicas;
    private javax.swing.JLabel caracteristicas1;
    private javax.swing.JLabel caracteristicas2;
    private javax.swing.JLabel cerrar;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel general;
    private javax.swing.JLabel general1;
    private javax.swing.JLabel general3;
    private javax.swing.JLabel habitat;
    private javax.swing.JLabel habitat1;
    private javax.swing.JLabel habitat2;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel pez;
    // End of variables declaration//GEN-END:variables
}
