/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal;

/**
 *
 * @author Enovasoft
 */

import DAO.AcuarioDAO;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

public class Tactil extends javax.swing.JFrame {

    /**
     * Creates new form Tactil
     */
    AcuarioDAO aDAO = new AcuarioDAO();
    ArrayList<String> id = new ArrayList<String>();
    ArrayList<String> name = new ArrayList<String>();
    ImageIcon Imagenes[] = new ImageIcon[3];
    String nombres[] = new String[3];
    int contador = 0;
    Seleccion seleccion = new Seleccion();

    public Tactil() throws SQLException {
        initComponents();
        id = id();
        name = name();
        for (int i = 0; i < 3; i++) {
            Imagenes[i] = new ImageIcon(getClass().getResource("/images/peces/fish" + i + ".png"));
            nombres[i] = "PEZCADO No. " + (i+1);
        } 
//        int i = 0;
//        for (String s : id) {
//            Imagenes[i] = new ImageIcon(getClass().getResource("/images/peces/fish" + Integer.parseInt(s) + ".png"));
//            i++;
//        }
//        int j = 0;
//        for (String s : name) {
//            nombres[j] = s;
//            j++;
//        }
        visor.setIcon(Imagenes[0]);
        nombre.setText(nombres[0]);
        Connection connection = Conexion.getConnection();
        if (connection != null) {
            System.out.print(connection);
        }
    }

    public ArrayList id() throws SQLException {
        id = aDAO.listarPeces();
        return id;
    }

    public ArrayList name() throws SQLException {
        name = aDAO.listarNombrePeces();
        return name;
    }

//    private void createObjects() {
//        
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        primera = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        prev = new javax.swing.JLabel();
        next = new javax.swing.JLabel();
        visor = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Acuario Mundo Aventura");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(255, 255, 255));
        setFocusable(false);
        setFocusableWindowState(false);
        setUndecorated(true);

        jLayeredPane1.setBackground(new java.awt.Color(255, 255, 255));
        jLayeredPane1.setAlignmentX(0.0F);
        jLayeredPane1.setAlignmentY(0.0F);
        jLayeredPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLayeredPane1.setPreferredSize(new java.awt.Dimension(1366, 768));

        primera.setAlignmentX(0.0F);
        primera.setAlignmentY(0.0F);
        primera.setMaximumSize(new java.awt.Dimension(1366, 768));
        primera.setMinimumSize(new java.awt.Dimension(1366, 768));
        primera.setOpaque(false);
        primera.setPreferredSize(new java.awt.Dimension(1366, 768));

        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mundoII.png"))); // NOI18N
        titulo.setAlignmentY(0.0F);

        prev.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        prev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/prev.png"))); // NOI18N
        prev.setAlignmentY(0.0F);
        prev.setRequestFocusEnabled(false);
        prev.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                prevMouseClicked(evt);
            }
        });

        next.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        next.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/next.png"))); // NOI18N
        next.setAlignmentY(0.0F);
        next.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nextMouseClicked(evt);
            }
        });

        visor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        visor.setAlignmentY(0.0F);
        visor.setMaximumSize(new java.awt.Dimension(720, 300));
        visor.setMinimumSize(new java.awt.Dimension(720, 300));
        visor.setPreferredSize(new java.awt.Dimension(720, 300));
        visor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                visorMouseClicked(evt);
            }
        });

        nombre.setBackground(new java.awt.Color(255, 255, 255));
        nombre.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        nombre.setForeground(new java.awt.Color(255, 255, 255));
        nombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back.png"))); // NOI18N
        nombre.setAlignmentY(0.0F);
        nombre.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        nombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nombreMouseClicked(evt);
            }
        });

        fondo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/acuario.jpg"))); // NOI18N
        fondo.setText("general");
        fondo.setAlignmentY(0.0F);
        fondo.setMaximumSize(new java.awt.Dimension(1366, 768));
        fondo.setMinimumSize(new java.awt.Dimension(1366, 768));
        fondo.setPreferredSize(new java.awt.Dimension(1366, 768));

        javax.swing.GroupLayout primeraLayout = new javax.swing.GroupLayout(primera);
        primera.setLayout(primeraLayout);
        primeraLayout.setHorizontalGroup(
            primeraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1366, Short.MAX_VALUE)
            .addGroup(primeraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(primeraLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(primeraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(primeraLayout.createSequentialGroup()
                            .addGap(518, 518, 518)
                            .addComponent(titulo))
                        .addGroup(primeraLayout.createSequentialGroup()
                            .addGap(100, 100, 100)
                            .addComponent(prev, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(920, 920, 920)
                            .addComponent(next, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(primeraLayout.createSequentialGroup()
                            .addGap(330, 330, 330)
                            .addComponent(nombre))
                        .addGroup(primeraLayout.createSequentialGroup()
                            .addGap(330, 330, 330)
                            .addComponent(visor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(fondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        primeraLayout.setVerticalGroup(
            primeraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 768, Short.MAX_VALUE)
            .addGroup(primeraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(primeraLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(primeraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(primeraLayout.createSequentialGroup()
                            .addGap(25, 25, 25)
                            .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(261, 261, 261)
                            .addGroup(primeraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(prev, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(next, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(74, 74, 74)
                            .addComponent(nombre))
                        .addGroup(primeraLayout.createSequentialGroup()
                            .addGap(345, 345, 345)
                            .addComponent(visor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(fondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jLayeredPane1.add(primera);
        primera.setBounds(0, 0, 1366, 768);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1366, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 768, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextMouseClicked
//        try {
//            // TODO add your handling code here:
//            id = aDAO.listarPeces();
//        } catch (SQLException ex) {
//            Logger.getLogger(Tactil.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        if (contador == id.size() - 1) {
        if (contador == 3) {
            contador = -1;
        }
        contador++;
        visor.setIcon(Imagenes[contador]);
        nombre.setText(nombres[contador]);
    }//GEN-LAST:event_nextMouseClicked

    private void prevMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prevMouseClicked
        // TODO add your handling code here:
//        try {
//            // TODO add your handling code here:
//            id = aDAO.listarPeces();
//        } catch (SQLException ex) {
//            Logger.getLogger(Tactil.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        if (contador == 0) {
        if (contador == -1) {
            contador = 3;
        }
        contador--;
        visor.setIcon(Imagenes[contador]);
        nombre.setText(nombres[contador]);
    }//GEN-LAST:event_prevMouseClicked

    private void visorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_visorMouseClicked
        // TODO add your handling code here:
        seleccion.setVisible(true);
        seleccion.setLocation(-5,0);
        Explode ex = new Explode( seleccion );
        ex.play();
        seleccion.emergente();
    }//GEN-LAST:event_visorMouseClicked

    private void nombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nombreMouseClicked
        // TODO add your handling code here:
        visorMouseClicked(evt);
    }//GEN-LAST:event_nombreMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fondo;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel next;
    private javax.swing.JLabel nombre;
    private javax.swing.JLabel prev;
    private javax.swing.JPanel primera;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel visor;
    // End of variables declaration//GEN-END:variables
}